In [2]:
S = ""
def connect(S,i):
    S = S + chr(i)
    return S


for i in range(65,91):
    S = connect(S,i)
    print(S)

A
AB
ABC
ABCD
ABCDE
ABCDEF
ABCDEFG
ABCDEFGH
ABCDEFGHI
ABCDEFGHIJ
ABCDEFGHIJK
ABCDEFGHIJKL
ABCDEFGHIJKLM
ABCDEFGHIJKLMN
ABCDEFGHIJKLMNO
ABCDEFGHIJKLMNOP
ABCDEFGHIJKLMNOPQ
ABCDEFGHIJKLMNOPQR
ABCDEFGHIJKLMNOPQRS
ABCDEFGHIJKLMNOPQRST
ABCDEFGHIJKLMNOPQRSTU
ABCDEFGHIJKLMNOPQRSTUV
ABCDEFGHIJKLMNOPQRSTUVW
ABCDEFGHIJKLMNOPQRSTUVWX
ABCDEFGHIJKLMNOPQRSTUVWXY
ABCDEFGHIJKLMNOPQRSTUVWXYZ


In [15]:
def level(i):
    temp = 1
    for j in range(1,i+1):
        temp *= j
    return temp

sum = 0
for i in range(1,4):
    sum  += level(i)
print(sum)

9


In [14]:
def recur(i):
    if i == 1:
        return 1
    else:
        return recur(i-1) *i
num = 0
for i in range(1,4):
    num += recur(i)

print(num)

9


In [24]:
def ADD(Persons):
    total_salary = 0
    for person in Persons:
        total_salary += person[3]
    return total_salary
def L2D(L):
    Dict ={}
    for person in L:
        Dict[person[0]] = person[1:4]
    return Dict

Persons=[["John",20,160,45000],["Mary",24,165,30000],['Lucy',25,170,35000]]
total_salary = ADD(Persons)
Dict =  L2D(Persons)
print(total_salary)
print(Dict)

110000
{'John': [20, 160, 45000], 'Mary': [24, 165, 30000], 'Lucy': [25, 170, 35000]}


In [ ]:
# 計算薪資總合，並傳回主程式
def ADD(L):

# 將 list 轉為字典，並傳回主程式
{"John":[20,160,45000],"Mary":[24,165,30000]}
def L2D(L):

Persons=[["John",20,160,45000],["Mary",24,165,30000],['Lucy',25,170,35000]]
S=ADD(Persons)
E=L2D(L)

In [25]:
class Person:
    def __init__(self,name,age):
        self.Name = name
        self.Age = age
        print("Mr." + self.Name)
        print("Age is " , age)
John = Person("John Smith",30)
Mary = Person("Mary Wang",25)

Mr.John Smith
Age is  30
Mr.Mary Wang
Age is  25


In [27]:
class Banks:
    def __init__(self,UName,Basic_money):
        self.name = UName
        self.money = Basic_money
    def store(self,inMoney):
        self.money += inMoney
        print("Total money is ",self.money)
    def take(self,outMoney):
        self.money -= outMoney
        print("Total money is ",self.money)
John = Banks("Johm Smith",100)
John.store(100)
John.take(50)

Total money is  200
Total money is  150


In [45]:
import os
cur_path = os.getcwd()
#print(cur_path)
with open("file2.txt","r",encoding = "UTF-8") as f:
    #content = f.read()
    content = f.readlines()
    print(content)

['Hello Python\n', '中文字測試\n', 'Welcome\n']


In [52]:
import os
cur_path = os.getcwd()
#print(cur_path)
with open("Exe.txt","r",encoding = "UTF-8") as file:
    #content = f.read()
    content = file.readlines()    
#print(content)
Data = [data.strip() for data in content]
#print(Data)
Data = [data.split('\t') for data in Data]
print(Data)
for person in Data:
    for item in person:
        print(item, end = "\t")
    print("")

[['姓名', '薪資', '性別'], ['張三', '30000', '1'], ['李四', '40000', '2'], ['王五', '35000', '1']]
姓名	薪資	性別	
張三	30000	1	
李四	40000	2	
王五	35000	1	


In [58]:
import numpy as np
a = np.array([1,2,3])
print(a.shape)
b = np.array(
    [[1,2],
    [3,4],
    [5,6]]
)
print(b.shape)

(3,)
(3, 2)


In [66]:
a = np.zeros((2,2))
print(a)
b = np.ones((3,3))
print(b)
c = np.eye((4))
print(c)
d = np.random.random((2,3))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.99935385 0.34099873 0.63523718]
 [0.82326565 0.01980447 0.15336785]]
